site_name: FRAM data
repo_url: https://github.com/NVE/fram-data
repo_name: NVE/fram-data

theme:
  name: "material"
  icon:
    repo: fontawesome/brands/github
  features:
    - content.code.copy      # Copy button
    - content.code.select    # Line selection
    - content.code.annotate  # Code annotations

nav:
  - index.md
  - data_validation.md
  - metadata.md
  - editing_profiles.md
  - reference.md

markdown_extensions:
- attr_list
- pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    linenums: true
    pygments_lang_class: true
    use_pygments: true
- pymdownx.superfences
- pymdownx.inlinehilite

plugins:
  - mkdocstrings:
     handlers:
        python:
          options:  
            show_submodules: true
            show_root_heading: true
            show_root_full_path: true
            show_signature_annotations: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            show_source: true
            show_object_full_path: false
  - mike
  - search
  - macros
  - table-reader

extra:
  version:
    provider: mike
  framlinks:
    nve: https://www.nve.no/english/
    fram: https://nve.github.io/fram/
    core: https://nve.github.io/fram-core/
    demo: https://nve.github.io/fram-demo/
    dataset: https://doi.org/10.5281/zenodo.17294466
